name: 'Build Cevixe GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Project 
      uses: cevixe/build@v1

    - name: Compress Artifact
      run: |
        tar -czvf dist.tar.gz ./dist
      shell: bash

    - name: Upload Artifact
      if: ${{ github.event_name == 'push'}}
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist.tar.gz